<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Nexus v0.5.0 by Bikossor</title>
    </head>
    <body>
        <main>
            <table id="nexus">
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Size</th>
                    <th>Mtime</th>
                    <th>Atime</th>
                </tr>
            </table>
        </main>
        <footer>
            <a href="https://github.com/Bikossor/Nexus" target="_blank">Nexus</a>
            &copy; André Lichtenthäler, 2019
        </footer>
        <script src="./assets/js/app.js"></script>
        <link rel="stylesheet" href="./assets/css/styles.css">
    </body>
</html>